name: Build and Push
on:
  push:
    branches: [main]

jobs:
  build-and-push-api:
    uses: ./.github/workflows/build-and-push-docker.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      context: 'api'
      target: 'release'
